---
title: "Projekt - Settlers of Catan stats"
author: "36544062 Marko Pongrac, 36540794 Marko Kukolj"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0. MOTIVACIJA I UVOD

<p>Kao ljubitelji društvene igre Catan te osobe koje ne vole gubiti, autori ovog rada izabrali su ovu temu s ciljem pronalaženja informacija, kako bi poboljšali svoju strategiju te šansu za pobjedu prilikom igranja s prijateljima. Zbog toga, ali i nekih iskustvenih pojava, ovaj rad pokušava dati odgovor na sljedeća pitanja:</p>
<ol start="1" style="margin-left: 5em;">
  <li>Je li kocka zaista poštena?</li>
  <li>Postoji li neka kombinacija resurs(a) na početnim susjednim poljima koja povećava vjerojatnost pobjede?</li>
  <li>Postoji li neka kombinacija broj(eva) na početnim susjednim poljima koja povećava vjerojatnost pobjede?</li>
  <li></li>
</ol>

\newpage
## 1. Je li kocka poštena?

TODO filler text

\newpage
## 2. Utjecaj početnih resursa na pobjedu

TODO filler text

\newpage
## 3. Utjecaj početnih brojeva na pobjedu

TODO filler text

----------------------------------------------
TODO lorem ipsum 
